### PR TITLE
getDropdownMenuNavitems on login

### LINKED ISSUE #7: Error on login if menu has item with "simpleLink" to not published page
**How to reproduce?**
- create a second menu with a 'simple link' menu item with a target that is not published.
- log out
- go to front page
- reload page
- log in
- go to location with the non default menu

**What happens?**
- Error on flattenToAppUrl:
NavLink lacks linkUrl 

**I propose to dispatch action 'getDropdownMenuNavitems' on login.**

```
const Navigation = ({ pathname, token, type, children }) => {

  ...

  useEffect(() => {
    dispatch(getDropdownMenuNavitems());
  }, [dispatch, token]);
```

### PR DESCRIPTION
**Pull request by ksuess**
Fixes https://github.com/collective/volto-dropdownmenu/issues/7

### CODE REVIEW

**Review by nzambello — CHANGES_REQUESTED** [review]
LGTM, but please use the hook to retrieve data from the store.
```const token = useSelector(state => state.userSession?.token)```

**Review by nzambello — APPROVED** [review]
LGTM, @giuliaghisini what do you think about this?

**Review by giuliaghisini — APPROVED** [review]
LGTM

**Review by giuliaghisini — APPROVED** [review]

**Review by nzambello — APPROVED** [review]
LGTM

**Pull request merged**
